### PR TITLE
Support direct calls and its unittest. Support python3 for unittest.

### PR DESCRIPTION
**Pull request by MagicFrogSJTU**
Unittest passed.

### CODE REVIEW

**Comment by MagicFrogSJTU** [comment]
Linked to this issue.
#15

**Review by brouberol — APPROVED** [review]
Thank you for the submission!

**Comment by MagicFrogSJTU** [comment]
> Thank you for the submission!

how is it going?

**Comment by brouberol** [comment]
I'm so sorry for the sizeable delay.. This somehow completely fell off my radar for years.  Thank you, and thanks to @Butanium for #17, which made me realize this PR had been sent out.

**Pull request merged**
